---
- hosts: localhost
  connection: local
  vars:
    whoami: "{{ lookup('env', 'USER') }}"
    user_home: "{{ lookup('env', 'HOME') }}"
    user_email: dtsomp@gmail.com
    full_name: Dimitris Tsompanidis
    vim_repo: https://github.com/dtsomp/vim.git
    mutt_repo: gogs@git.tsomp.net:dtsomp/muttrc.git
    tmux_repo: https://github.com/dtsomp/tmux.git
  roles:
    - debian
    - console-tools
    - console-personal
    - desktop
    - dev
    - network-tools
