---
- name: Firefox repo
  become: true
  template: src=firefox.list
            dest=/etc/apt/sources.list.d/firefox.list

- name: Install desktop applications
  become: true
  apt: name={{item}} state=present
  with_items:
   - firefox-esr
   - chromium
   - keepassx
   - empathy
   - network-manager-openvpn-gnome
   - openvpn
   - libpango1.0-0
   - cryptsetup

- include: spideroak.yml
- include: dropbox.yml
- include: keybase.yml
- include: firefox.yml
