---
- name: Debian repositories repo
  become: true
  template: src=sources.list
            dest=/etc/apt/sources.list
  register: debianrepo

- name: Refresh Debian repos
  become: root
  command: apt-get -qq update
  when: debianrepo.changed
