---

- name: Install cli tools for personal use
  become: root
  apt: name={{item}} state=present
  with_items:
    - mutt
    - git

- include: sshkey.yml
- include: mutt.yml
- include: aliases.yml
- include: git.yml

