---

- name: Clone tmux config repo
  git: 
    repo: "{{ tmux_repo }}"
    dest: "{{ user_home }}/tmuxrc"
    update: no 

- file:
    src: "{{ user_home }}/tmuxrc/tmux.conf"
    dest: "{{ user_home }}/.tmux.conf"
    state: link 
