---

- stat: path=/home/dtsomp/vimrc
  register: vimrc

- name: Clone vim config
  sudo: no
  command: git clone {{ vimrepo }} /home/dtsomp/vimrc
  when: vimrc.stat.exists == False

- name: Pull vim repo
  sudo: no
  command: git pull
  args:
    chdir: /home/dtsomp/vimrc
  when: vimrc.stat.exists == True

- file: 
    src: '/home/dtsomp/vimrc/vimrc'
    dest: '/home/dtsomp/.vimrc'
    state: link
