---
- name: install basics
  become: root
  apt: name={{item}} state=present
  with_items:
   - curl
   - vim
   - make
   - wget
   - lynx
   - mutt
   - powertop
   - puppet
   - git
   - tmux

- include: sshkey.yml
- include: tmux.yml
