---

- include_vars: vars.yml

- name: Check if Virtualbox is installed
  command: dpkg-query -s virtualbox-{{ virtualbox_version }}
  register: vboxcheck
  failed_when: vboxcheck.rc > 1
  check_mode: no

- name: Add virtualbox repo
  become: true
  template: src=virtualbox.list
            dest=/etc/apt/sources.list.d/virtualbox.list
  when: vboxcheck.rc == 1
  
- name: Get Oracle pub key
  get_url:
    url: "{{ oracle_key_url }}"
    dest: "{{ user_home }}/Downloads/oracle_vbox.asc"
  when: vboxcheck.rc == 1

- name: Add Oracle pub key
  become: true
  command: apt-key add {{ user_home }}/Downloads/oracle_vbox.asc
  when: vboxcheck.rc == 1

- name: Install Virtualbox  
  become: true
  apt: name={{item}} state=present update_cache=yes
  with_items:
    - virtualbox-{{ virtualbox_version }}
